# Generated by Django 5.1.4 on 2025-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_alter_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
